### ISSUE TITLE
README.md file in when-are-pubsub-messages-acked

### ISSUE THREAD

**Issue by XiaoxiaLin** [gxercavins/dataflow-samples#2]
a typo in the README.md

should change "input-topic" to "input-sub" in the screenshot below: 
![screen shot 2018-10-31 at 19 56 01](https://user-images.githubusercontent.com/7916863/47811832-0b7da400-dd47-11e8-9824-3ce41a5ab254.png)

$ gcloud pubsub subscriptions pull input-sub --limit 10 --auto-ack

**Comment by XiaoxiaLin** [comment]
some typo when pulling msg from input-sub after publish message "test".

**Comment by gxercavins** [comment]
Thanks, corrected now
